# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kCV1eFlu4ToRHBMrkYusMqzdwKs3NO13
"""



"""Hello world!"""

$y(x)=e^x$

"Hello world!"

stg = "Hello world!"

type (stg)

print("Hello world!")

